
["blood spray settings"]
	#How long in ticks (20 ticks = 1 second) until a blood spatter despawns.
	#Range: 0 ~ 100000
	despawn_time = 2000
	#The maximum amount of blood spatters that can exist in the world at once.
	#Range: 0 ~ 10000
	max_spatters = 2000
	#Whether or not blood chunks should replace the poof particles when an entity dies.
	show_blood_chunks = true
	#The maximum amount of blood chunks that can exist in the world at once.
	#Range: 0 ~ 10000
	max_chunks = 1000
	#The maximum amount of distance a player can be away from a damaged entity for blood to spray.
	#Range: 0 ~ 1000
	distance_to_players = 100
	#Define what mobs 'bleed' solid bits. This is mainly skeletons. Instead of bleeding they will just shoot out colored bits,and instead of getting bloodier when damaged, they will lose pixels.
	solid_entities = ["minecraft:skeleton", "minecraft:skeleton_horse", "minecraft:wither_skeleton", "minecraft:wither", "minecraft:shulker"]

